name: Publish Blazor App to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build and publish
      run: |
        dotnet build --configuration Release
        dotnet test --configuration Release --no-build
        dotnet publish src/BlazorApp -c Release -o release --nologo
        
    - name: Update base href
      shell: pwsh
      run: |
        $indexHtml = "release/wwwroot/index.html"
        $content = Get-Content -Path $indexHtml -Raw
        $repository = "${{ github.repository }}" -split '/', 2 | Select-Object -Last 1
        if ($content -match '<base href="/"') {
          $content = $content -replace '<base href="/"', "<base href=`"/$repository/`""
        }
        # Check if empty base tag exists
        elseif ($content -match '<base\s*/>') {
          $content = $content -replace '<base\s*/>', "<base href=`"/$repository/`" />"
        }
        # Check if base tag with dynamic script exists
        elseif ($content -match '<base\s*>') {
          $content = $content -replace '<base\s*>', "<base href=`"/$repository/`">"
        }
        # If no base tag is found, add one
        else {
          $content = $content -replace '<head>', "<head>`n    <base href=`"/$repository/`" />"
        }
        Set-Content -Path $indexHtml -Value $content -NoNewline
        Write-Host "Base href has been updated to /$repository/"
        
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: release/wwwroot
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        clean: true
